f = open("test.txt", "r")
#f = open("test.txt", "rb")
#f = open("test.txt", "w")
#f = open("test.txt", "wb")
#f = open("test.txt", "a")
#f = open("test.txt", "r+")
print(f.name)
print(f.mode)
f.close()
